# -*- coding: utf-8 -*-
"""ciclos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Iya-mVgJ1Yvtih9ERmJzGDIPrM-8kRL

#Ciclos
Ciclo for
Ciclo While
"""

for variable in secuencia:
  #bloque de código

print ("Hola mundo")

numero=5
for i in range(numero):
  print("Hola mundo")

for i in range(1, 11):
  print (i)

suma=0
for i in range(1, 101):
  suma +=i

print("la suma del 1 al 100 es: ", suma)

for i in range(10):
  print ("inicio : ", i)
  if i==5:
    break
  print (i)

for i in range(10):
  print ("inicio : ", i)
  if i==5:
    continue
  print (i)

"""#Ciclo While"""

while condición:
  #Bloque de código

contador=1
while contador <=5:
  print ("Contador: ", contador)
  contador +=1

# El usuario debe adivinar el numero secreto
numero_secreto = 7
while True:
  intento = int(input("Adivina el número: "))
  if intento == numero_secreto:
    print ("Adivinaste!!")
    break
  else:
    print("Intenta de  nuevo ")

"""**`Escribe un programa que imprima los múltiplos de 3 del 1 al 50.`**"""

for i in range (1, 51):
  if i % 3==0:
    print(i)

"""Escribe un programa con un ciclo while que solicite una contraseña hasta que sea correcta"""

contrasena = "123"
intento =""
while intento!=contrasena:
  intento = input("Introduce la contraseña: ")
print ("Contraseña correcta!")

"""**Sumar los numero pares del 1 al 100**"""

suma = 0
for i in range (2,101, 2):
  suma +=i
print ("La suma de los numeros pares entre 1 y 100 es: ", suma)

suma = 0
for i in range (1,101):
  if i%2==0:
    suma +=i
print ("La suma de los numeros pares entre 1 y 100 es: ", suma)

suma = sum(range (2, 1001,2))
print ("La suma de los numeros pares entre 1 y 100 es: ", suma)