# -*- coding: utf-8 -*-
"""Declarar._variables2ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1beHzr8FnAFHgBHOolkW5jXWOA0510Gy8

# **Este codigo es para explicar definición de variables**
"""

# DECLARAR UNA VARIABLE

#Entero int
numero = 87
print (numero)

#Flotante float
flotante = 58.6
print (flotante)

#String str
String = "Claudia"
print (String)
dias_de_la_semana = ["lunes", "martes", "miercoles", "jueves", "viernes"]
#Tipo Listas
lista_frutas = ["mango","pina","uva", 56, 78.9, dias_de_la_semana, "fresa", "banano"]
print(lista_frutas)

print (lista_frutas[2])
print (lista_frutas[-2])
lista_frutas[2] = "sandia"
print (lista_frutas)