# -*- coding: utf-8 -*-
"""Declara_variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUMuMvtbCAztG-dpK593ZnZ9vaNQwClM
"""

# DECLARAR UNA VARIABLE

#Entero int
numero = 87 + 9
#Flotante float
flotante = 58.6
#String str
String = "Daniela"
print (numero)
#print imprime
print (flotante)
print (String)


#listas list

lista_frutas = ["mango","pina","uva", "fresa", "banano"]
print(lista_frutas)
print ("la posición 3 del listado de frutas es:")
print(lista_frutas[2])