# -*- coding: utf-8 -*-
"""Funciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bdTpkZt_oW8xmXZsY6TwoDQBRLdV7S-F

#Definición de una función
"""

# Esta función no recibe parámetros
def saludar():
  '''Esta función saluda'''
  print("Hola! Espero que tengas un excelente día!")

# Llamamos a la función
saludar()

"""##Parámetros en una función"""

# Esta función si recibe parámetros
def crear_usuario(nombre_usuario):
  '''Crea un usuario para el sistema crear_usuario("Ricardo") -> "usuario creado"'''
  print("Creando usuario...")
  print(f"Usuario creado correctamente: {nombre_usuario}")

# Llamamos a la función
crear_usuario("Ricardo")

# Si no coloco parámetros a una función que lo requiere
# obtendré un error
crear_usuario()

"""## Retorno de información de una función"""

def sumar(num_1, num_2, num_3):
  '''Suma 3 números y devuelve el resultado'''
  resultado = num_1 + num_2 + num_3
  return resultado

resultado_suma = sumar(10,20,30)
print(f"El resultado de la suma es {resultado_suma}")

"""#Parámetros por defecto en funciones"""

def grabar_informacion(primer_nombre, edad, segundo_nombre=""):
  '''Guarda la información de una persona'''
  print("Guardando información...")
  print(f"La información {primer_nombre}, {segundo_nombre} y {edad} fue guardada")

grabar_informacion(primer_nombre=4,edad=33, segundo_nombre="Goku")

def multiplicar(num_1: int, num_2: int):
  '''Multiplica dos números enteros'''
  print("combración de que los números son enteros")
  if type(num_1) == int:
    resultado = num_1 * num_2
    return resultado
  else:
    print("Error")

def multiplicar(num_1: int, num_2: int):
  '''Multiplica dos números enteros'''
  print("combración de que los números son enteros")
  if isinstance (num_1, int):
    resultado = num_1 * num_2
    return resultado
  else:
    print("Error")

result = multiplicar(5.3,2)
print(result)

"""#F-strings"""

nombre = "ricardo"
print("Mi nombre es "+nombre+"soy ejecutor técnico")
print(f"Mi nombre es {nombre}, soy ejecutor técnico")

"""Condicionales
Comparadore ==, >, <, !=

if si, , elif= sino, eles entonces
"""

# Evaluar si un numero es mayor que el otro
num1= int (input("Digite el numero 1: "))
num2= int (input("Digite el numero 2: "))
#comparar

if num1>num2:
  print ("El numero 1 es mayor que el 2. ")
elif num1<num2:
  print ("El numero 1 no es mayor que el 2. ")
else:
  print("Los numeros son iguales. ")

"""Verifica si un número está entre 1 y 100."""

numero3= int (input("Digita un numero "))

if 1<= numero3 <=100:
  print ("El numero está entre 1 y 100 ")
else:
  print ("El numero no está entre 1 y 100 ")

numero3= int (input("Digita un numero "))


if numero3 in range (1, 101):
  print ("El numero está entre 1 y 100 ")
else:
  print ("El numero no está entre 1 y 100 ")

"""Pida un numero al usuario y determinar si es positivo, negativo o 0."""

numero3= int (input("Digita un numero "))

#Evaluar el numero
if numero3 >0:
  print (f"EL numero {numero3} es positivo ")
elif numero3 <0:
  print (f"El numero {numero3} es negativo ")
else:
  print (f"El numero {numero3} es 0")

"""1. Verifica si un número es múltiplo de 5.
2. Determina si un año es bisiesto.
3. Determina si un número está fuera del rango [10, 50].
"""

numero = int (input("Digite un numero: "))
#Evaluar la condición

if numero % 5 ==0:
  print (f"El número {numero} es múltipli de 5. ")
else:
  print (f"El numero {numero} No es múltiplo de 5. ")

an= int (input ("Digite el año a evaluar: "))

#Condición

if (an % 400 == 0) or (an % 4==0 and an % 100 !=0):
  print (f" {an} es un año bisiesto")
else:
  print (f"{an} no es un año bisiesto ")

#Determina si un número está fuera del rango [10, 50].
numero= int (input("Digite un numero: "))
if numero in range (10, 51):
  print (f"El {numero} esta dentro del rango de [10, 50] ")
else:
  print (f"El {numero} No está en el rango de [10, 50] ")

# Verificar si un usuario tiene cedula y puede votar
edad = int (input("Digite su edad "))
tiene_cedula = True

if edad >= 18 and tiene_cedula:
  print ("Puede votar")
else:
  print ("No puede votar")

#Debo llevar sombrill o no

llueve = True
nublado = False

if llueve or not nublado:
  print ("Llevar sombrilla por que va a llover ")
else:
  print ("Es un día despejado ")

"""Validar si un usaurio está bloqueado (si/no)"""

bloqueado = False

if not bloqueado:
  print ("El usuario está bloqueado")
else:
  print ("Acceso permitido")

"""#Ejercicio
Escribir un programa que pida al usuario un número entero y muestre por pantalla si es par o impar y que imprima cual es el mayor de los dos.
"""

def verificar_paridad (num):
  if num % 2==0:
    return "par"
  else:
    return "impar"

def nummayor (num1, num2):
  if num1>num2:
    return num1
  elif num2>num1:
    return num2
  else:
    return 0

num1 = int (input("Ingrese el primer numero: "))
num2 = int (input("Ingrese el segundo numero: "))

print (f"{num1} es {verificar_paridad(num1)} ")
print (f"{num2} es {verificar_paridad(num2)}")

mayor= nummayor (num1, num2)
if mayor==0:
  print ("Ambos numeros son iguales")
else:
  print(f"El numero mayor es: {mayor}")

num1 = int (input("Ingrese el primer numero: "))
num2 = int (input("Ingrese el segundo numero: "))

if num1 % 2==0:
    print (f"El numero {num1} es par ")
else:
    print (f"El numero {num1} es impar ")

if num2 % 2==0:
    print (f"El numero {num2} es par ")
else:
    print (f"El numero {num2} es impar ")

if num1>num2:
    print (f"El numero {num1} es mayor que {num2} ")
elif num2>num1:
    print (f"El numero {num1} es menor que {num2} ")
else:
    print (f"Son iguales ")