# -*- coding: utf-8 -*-
"""grafico26_marzo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mDBivr-xwmQrlS5S-K1h7HVgsQQSZNO
"""

from __future__ import print_function
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print ("versión de pandas : ", pd.__version__)
print ("versión de numpy : ", np.__version__)
print ("version de matplotlib : ", plt.matplotlib.__version__)

df= pd.read_csv("/content/datasets/WorldCups (1).csv")
df

