# -*- coding: utf-8 -*-
"""Retos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Ipz6aaZ7aCI3FZEJK_c-6LjdGhhC-Km

## Reto 1: Variables y Tipos de Datos

**Descripción:**

1.  Crea una variable llamada `nombre` y asígnale tu nombre (como una cadena de texto).
2.  Crea una variable llamada `edad` y asígnale tu edad (como un número entero).
3.  Crea una variable llamada `altura` y asígnale tu altura en metros (como un número decimal, por ejemplo, 1.75).
4.  Crea una variable llamada `mayor_de_edad` y asígnale un valor booleano (`True` si eres mayor de edad, `False` si no lo eres).
5.  Imprime cada variable en una línea separada, usando la función `print()`.

**Resultado Esperado:**

Tu Nombre

Tu Edad

Tu Altura

True o False (según corresponda)
"""



"""## Reto 2: Manejo de Listas

**Descripción:**

1.  Crea una lista llamada `frutas` que contenga los siguientes elementos: "manzana", "banana", "naranja", "uva", "kiwi".
2.  Imprime el segundo elemento de la lista (recuerda que la indexación en Python comienza en 0).
3.  Agrega "pera" al final de la lista.
4.  Elimina "naranja" de la lista.
5.  Imprime la lista modificada.

**Resultado Esperado:**

banana

['manzana', 'banana', 'uva', 'kiwi', 'pera']
"""



"""## Reto 3: Ciclo `for`

**Descripción:**

1.  Crea una lista llamada `numeros` que contenga los números del 1 al 10.
2.  Utiliza un ciclo `for` para iterar sobre la lista `numeros` e imprimir cada número multiplicado por 2.

**Resultado Esperado:**

2
4
6
8
10
12
14
16
18
20
"""



"""## Reto 4: Condicionales

**Descripción:**

1.  Crea una variable llamada `calificacion` y asígnale un valor numérico entre 0 y 10 (por ejemplo, 7).
2.  Utiliza una estructura condicional (`if`, `elif`, `else`) para determinar si la calificación es:
    *   "Sobresaliente" (si es 9 o 10)
    *   "Notable" (si está entre 7 y 8, inclusive)
    *   "Aprobado" (si es 6)
    *   "Reprobado" (si es menor que 6)
3.  Imprime el resultado.

**Resultado Esperado (ejemplo con calificación = 7):**

Notable
"""



"""## Reto 5: Combinando Conceptos

**Descripción:**

1.  Crea una lista llamada `palabras` que contenga varias palabras (al menos 5).
2.  Utiliza un ciclo `for` para iterar sobre la lista.
3.  Dentro del ciclo, para cada palabra, verifica si su longitud es mayor que 5.
    *   Si es mayor que 5, imprime la palabra en mayúsculas.
    *   Si no es mayor que 5, imprime la palabra en minúsculas.

**Resultado Esperado:**

python -> PYTHON

hola -> hola
"""



"""#Reto 6: Filtrado de Números con Entrada de Usuario

**Descripción:**

1.  Pide al usuario que ingrese un número entero (llamémoslo `limite`). Usa `input()` para obtener este número y asegúrate de convertirlo a un entero usando `int()`.
2.  Crea una lista llamada `numeros` que contenga los números del 1 al 20 (o un rango mayor si quieres).
3.  Utiliza un ciclo `for` para iterar sobre la lista `numeros`.
4.  Dentro del ciclo, verifica si cada número es menor que el `limite` ingresado por el usuario.
    *   Si es menor, imprime el número.
    *   Si es mayor o igual, no imprimas nada.
5.  Después del ciclo, si *ningún* número fue menor que `limite`, imprime un mensaje que diga: "Ningún número fue menor que el límite." (Esto requiere una variable adicional para controlar si se imprimió algún número o no).

**Resultado Esperado (ejemplo, si el usuario ingresa 12):**

1

2

3

4

5

6

7

8

9

10

11
"""

