# -*- coding: utf-8 -*-
"""Tipos_de_variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Urrp8ez1tznTKjrVNJ42C7xQhjR5OUhw
"""

nombre = "Ana"
edad = 25
altura = 1.70

frutas = ["manzana", "banana", "cereza"]
print(frutas)

frutas = ["manzana", "banana", "cereza"]
print(frutas[0], frutas [1])  # Primer elemento
print(frutas[-1]) # Último elemento

print(frutas[1])  # Primer elemento

frutas = ["manzana", "banana", "cereza"]
for fruta in frutas:
    print(fruta)
    len(frutas)
    print(len (frutas))